# Generated by Django 3.1.6 on 2021-05-14 08:29

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210513_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[api.models.num_pages_range_validation]),
        ),
    ]
