# Generated by Django 3.1.6 on 2021-05-14 16:53

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos', validators=[utils.validators.validate_size, utils.validators.validate_extension]),
        ),
    ]
